//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAnt.MSNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAnt.MSNet.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;todir&apos; should be set when using the &lt;assemblies&gt; element to specify the list of PE files to disassemble..
        /// </summary>
        internal static string NA3001 {
            get {
                return ResourceManager.GetString("NA3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;input&apos; attribute and the &lt;assemblies&gt; element cannot be combined..
        /// </summary>
        internal static string NA3002 {
            get {
                return ResourceManager.GetString("NA3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the &apos;output&apos; or &apos;todir&apos; attribute should be set..
        /// </summary>
        internal static string NA3003 {
            get {
                return ResourceManager.GetString("NA3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;output&apos; and &apos;todir&apos; attribute cannot both be set..
        /// </summary>
        internal static string NA3004 {
            get {
                return ResourceManager.GetString("NA3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string NA3005 {
            get {
                return ResourceManager.GetString("NA3005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output file for &apos;{0}&apos; could not be determined..
        /// </summary>
        internal static string NA3006 {
            get {
                return ResourceManager.GetString("NA3006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start service {0} on computer &apos;{1}&apos;..
        /// </summary>
        internal static string NA3007 {
            get {
                return ResourceManager.GetString("NA3007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot stop service {0} on computer &apos;{1}&apos;..
        /// </summary>
        internal static string NA3008 {
            get {
                return ResourceManager.GetString("NA3008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pause service {0} on computer &apos;{1}&apos;..
        /// </summary>
        internal static string NA3009 {
            get {
                return ResourceManager.GetString("NA3009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pause service {0} on computer &apos;{1}&apos; as its not currently started..
        /// </summary>
        internal static string NA3010 {
            get {
                return ResourceManager.GetString("NA3010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pause service {0} on computer &apos;{1}&apos; as it does not support the pause and continue mechanism..
        /// </summary>
        internal static string NA3011 {
            get {
                return ResourceManager.GetString("NA3011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot continue service {0} on computer &apos;{1}&apos;..
        /// </summary>
        internal static string NA3012 {
            get {
                return ResourceManager.GetString("NA3012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot continue service {0} on computer &apos;{1} as its not currently started..
        /// </summary>
        internal static string NA3013 {
            get {
                return ResourceManager.GetString("NA3013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot continue service {0} on computer &apos;{1} as it does not support the pause and continue mechanism..
        /// </summary>
        internal static string NA3014 {
            get {
                return ResourceManager.GetString("NA3014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot continue service {0} on computer &apos;{1} as its not currently running or paused..
        /// </summary>
        internal static string NA3015 {
            get {
                return ResourceManager.GetString("NA3015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disassembling &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string String_Disassembling {
            get {
                return ResourceManager.GetString("String_Disassembling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has been updated, disassembling..
        /// </summary>
        internal static string String_FileHasBeenUpdated {
            get {
                return ResourceManager.GetString("String_FileHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file &apos;{0}&apos; does not exist, disassembling..
        /// </summary>
        internal static string String_OutputFileDoesNotExist {
            get {
                return ResourceManager.GetString("String_OutputFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;rebuild&apos; attribute set to true, disassembling..
        /// </summary>
        internal static string String_RebuildAttributeSetToTrue {
            get {
                return ResourceManager.GetString("String_RebuildAttributeSetToTrue", resourceCulture);
            }
        }
    }
}
