version: 0.95.{build}

image: Visual Studio 2015

branches:
  only:
    - master
    - develop

environment:
  # Visual Studio 10 2010
  VS_VERSION: 100

  matrix:
    - TARGET: net-2.0
    - TARGET: net-3.5
    - TARGET: net-3.5
    - TARGET: net-4.0
    - TARGET: net-4.5

matrix:
  allow_failures:
    - branch: master
  fast_finish: true

platform:
  - x64
  - x86

configuration:
  - Debug


build_script:
  - echo build_script
  - if "%VS_VERSION%" == "100" if "%platform%" == "x86" set path="%path%;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\"
  - if "%VS_VERSION%" == "100" if "%platform%" == "x64" set path="%path%;C:\Program Files\Microsoft Visual Studio 10.0\VC\bin\"
  - nmake -f Makefile.nmake install prefix="c:\Program Files" TARGET=%TARGET%