version: 0.95.{build}

image: Visual Studio 2015

branches:
  only:
    - master
    - develop

shallow_clone: true
clone_depth: 1

environment:
  # Visual Studio 10 2010
  VSVER: 10

  matrix:
    - TARGET: net-2.0
    - TARGET: net-3.5
    - TARGET: net-3.5
    - TARGET: net-4.0
    - TARGET: net-4.5

matrix:
  allow_failures:
    - branch: master
    - configuration: x64
  fast_finish: true

platform:
  - X64
  - X86

configuration:
  - Debug


build_script:
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - if "%VS_VERSION%" == "100" if "%platform%" == "x86" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%VS_VERSION%" == "100" if "%platform%" == "x64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%VS_VERSION%" == "100" if "%platform%" == "x64" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - nmake -f Makefile.nmake install prefix="c:\Program Files" TARGET=%TARGET%