environment:
  NEXT_VERSION: 0.95
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  SONAR_DOTNET_ENABLE_CONCURRENT_EXECUTION: true
  
  matrix:
    - job_name: Windows build
      appveyor_build_worker_image: Visual Studio 2019
    - job_name: Linux build
      appveyor_build_worker_image: Ubuntu
    - job_name: MacOS build
      appveyor_build_worker_image: macOS

platform: Any CPU
configuration: Debug

branches:
  only:
    - master

matrix:
  fast_finish: true

init:
  - git config --global core.autocrlf true

# job-specific configurations
for:
  - matrix:
    only:
      - job_name: Windows build
    install:
      - choco install -y chocolatey-dotnetfx.extension
      - choco install -y sonarscanner-msbuild-net46

    before_build:
      - set JAVA_HOME=C:\Program Files\Java\jdk13
      - set PATH=%JAVA_HOME%\bin;%PATH%

    build_script:
      - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { SonarScanner.MSBuild.exe begin /k:"nant2" /o:"savornicesei-github" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$env:SQTOKEN" /d:"sonar.analysis.mode=preview" /d:"sonar.pullrequest.key=$env:APPVEYOR_PULL_REQUEST_NUMBER" /d:"sonar.github.repository=https://github.com/NAnt2/NAnt2" /d:sonar.cs.nunit.reportsPaths="reports\NAnt.Tests.xml" /d:sonar.cs.opencover.reportsPaths="reports\coverage.opencover.xml" }
      - ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { SonarScanner.MSBuild.exe begin /k:"nant2" /o:"savornicesei-github" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$env:SQTOKEN" /d:"sonar.github.repository=https://github.com/NAnt2/NAnt2" /d:"sonar.branch.name=$env:APPVEYOR_REPO_BRANCH" /v:$env:NEXT_VERSION /d:sonar.cs.nunit.reportsPaths="reports\NAnt.Tests.xml" /d:sonar.cs.opencover.reportsPaths="reports\coverage.opencover.xml" }
      - ps: .\build.ps1 -Tasks Build -BuildConfiguration {Debug} -Rebuild

    test_script:
      - ps: .\build.ps1 -Tasks Test -BuildConfiguration {Debug} -WithCoverage

    after_test:
      - SonarScanner.MSBuild.exe end /d:"sonar.login=%SQTOKEN%"
      - ps: |
          $wc = New-Object 'System.Net.WebClient'
          $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path reports\NAnt.Tests.xml))

  - matrix:
    only:
      - job_name: Linux build
    build_script:
      - ps: .\build.ps1 -Tasks Build -BuildConfiguration {Debug} -Rebuild
    test_script:
      - ps: .\build.ps1 -Tasks Test -BuildConfiguration {Debug} -WithCoverage

  - matrix:
    only:
      - job_name: MacOS build
    build_script:
      - ps: .\build.ps1 -Tasks Build -BuildConfiguration {Debug} -Rebuild
    test_script:
      - ps: .\build.ps1 -Tasks Test -BuildConfiguration {Debug} -WithCoverage

#---------------------------------#
#        global handlers          #
#---------------------------------#
on_success:
  - ps: |    
      if($true)
      {
        Write-Host 'Succesfuly build'
      }

on_failure:
  - ps: |    
      if($true)
      {
        Write-Host "Build failed with exit code $LASTEXITCODE! " -ForegroundColor Red -NoNewline
      } 
