language: c
sudo: enabled

install:
  - ./scripts/install-mono.sh

env:
  - TARGET=mono-2.0 MCS="mcs -sdk:2"
  - TARGET=mono-4.0 MCS="mcs -sdk:4"

script:
  - mono --version
  - make clean run-test TARGET=$TARGET MCS="$MCS"