//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAnt.DotNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAnt.DotNet.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly attribute with type &apos;{0}&apos; could not be loaded..
        /// </summary>
        internal static string NA2001 {
            get {
                return ResourceManager.GetString("NA2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid type {0} was specified..
        /// </summary>
        internal static string NA2002 {
            get {
                return ResourceManager.GetString("NA2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of assembly attribute &apos;{0}&apos; cannot be set as it has no constructor accepting a primitive type or string..
        /// </summary>
        internal static string NA2003 {
            get {
                return ResourceManager.GetString("NA2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyInfo file &apos;{0}&apos; could not be generated..
        /// </summary>
        internal static string NA2004 {
            get {
                return ResourceManager.GetString("NA2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly attribute &apos;{0}&apos; has no default public constructor..
        /// </summary>
        internal static string NA2005 {
            get {
                return ResourceManager.GetString("NA2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; cannot be converted to type &apos;{1}&apos; of assembly attribute {2}..
        /// </summary>
        internal static string NA2006 {
            get {
                return ResourceManager.GetString("NA2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified code language is not supported..
        /// </summary>
        internal static string NA2007 {
            get {
                return ResourceManager.GetString("NA2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating a JSCript AssemblyInfo file is not supported at this moment..
        /// </summary>
        internal static string NA2008 {
            get {
                return ResourceManager.GetString("NA2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string NA2009 {
            get {
                return ResourceManager.GetString("NA2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manifest resource name for &apos;{0}&apos; could not be determined..
        /// </summary>
        internal static string NA2010 {
            get {
                return ResourceManager.GetString("NA2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &quot;{0}&quot; for attribute &quot;debug&quot;..
        /// </summary>
        internal static string NA2011 {
            get {
                return ResourceManager.GetString("NA2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either &apos;keyfile&apos; or &apos;keycontainer&apos; must be specified..
        /// </summary>
        internal static string NA2012 {
            get {
                return ResourceManager.GetString("NA2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;target&apos; is a required attribute of &lt;{0} ... /&gt;..
        /// </summary>
        internal static string NA2013 {
            get {
                return ResourceManager.GetString("NA2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string NA2014 {
            get {
                return ResourceManager.GetString("NA2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine output file from target &apos;{0}&apos;..
        /// </summary>
        internal static string NA2015 {
            get {
                return ResourceManager.GetString("NA2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate type {0}..
        /// </summary>
        internal static string NA2016 {
            get {
                return ResourceManager.GetString("NA2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not a licensed component..
        /// </summary>
        internal static string NA2017 {
            get {
                return ResourceManager.GetString("NA2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create license for type &apos;{0}&apos;..
        /// </summary>
        internal static string NA2018 {
            get {
                return ResourceManager.GetString("NA2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create license file for &apos;{0}&apos;..
        /// </summary>
        internal static string NA2019 {
            get {
                return ResourceManager.GetString("NA2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one included assembly..
        /// </summary>
        internal static string NA2020 {
            get {
                return ResourceManager.GetString("NA2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create NDoc Project..
        /// </summary>
        internal static string NA2021 {
            get {
                return ResourceManager.GetString("NA2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read ndoc namespace summary file &apos;{0}&apos;..
        /// </summary>
        internal static string NA2022 {
            get {
                return ResourceManager.GetString("NA2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error building documentation..
        /// </summary>
        internal static string NA2023 {
            get {
                return ResourceManager.GetString("NA2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading documenter &apos;{0}&apos;. There are no NDoc documenters available..
        /// </summary>
        internal static string NA2024 {
            get {
                return ResourceManager.GetString("NA2024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading documenter &apos;{0}&apos; from available documenters ({1}). Is the NDoc documenter assembly available?.
        /// </summary>
        internal static string NA2025 {
            get {
                return ResourceManager.GetString("NA2025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;output&apos; attribute is incompatible with fileset use..
        /// </summary>
        internal static string NA2026 {
            get {
                return ResourceManager.GetString("NA2026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource generator needs either an input attribute, or a non-empty fileset..
        /// </summary>
        internal static string NA2027 {
            get {
                return ResourceManager.GetString("NA2027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading assembly &apos;{0}&apos;..
        /// </summary>
        internal static string NA2028 {
            get {
                return ResourceManager.GetString("NA2028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation failed:.
        /// </summary>
        internal static string NA2029 {
            get {
                return ResourceManager.GetString("NA2029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid main class &apos;{0}&apos;..
        /// </summary>
        internal static string NA2030 {
            get {
                return ResourceManager.GetString("NA2030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing entry point..
        /// </summary>
        internal static string NA2031 {
            get {
                return ResourceManager.GetString("NA2031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entry point declaration (should be static)..
        /// </summary>
        internal static string NA2032 {
            get {
                return ResourceManager.GetString("NA2032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entry point declaration (wrong number of parameters)..
        /// </summary>
        internal static string NA2033 {
            get {
                return ResourceManager.GetString("NA2033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entry point declaration (invalid parameter type &apos;{0}&apos;, &apos;{1}&apos; expected)..
        /// </summary>
        internal static string NA2034 {
            get {
                return ResourceManager.GetString("NA2034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure executing script..
        /// </summary>
        internal static string NA2035 {
            get {
                return ResourceManager.GetString("NA2035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeDomProvider for &apos;{0}&apos; could not be created..
        /// </summary>
        internal static string NA2036 {
            get {
                return ResourceManager.GetString("NA2036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; could not be loaded with partial name..
        /// </summary>
        internal static string NA2037 {
            get {
                return ResourceManager.GetString("NA2037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not a valid CodeDomProvider..
        /// </summary>
        internal static string NA2038 {
            get {
                return ResourceManager.GetString("NA2038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly attribute with type &apos;{0}&apos; could not be loaded. Should it be &apos;{0}Attribute&apos;?.
        /// </summary>
        internal static string NA2039 {
            get {
                return ResourceManager.GetString("NA2039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (loaded).
        /// </summary>
        internal static string String_AssemblyLoaded {
            get {
                return ResourceManager.GetString("String_AssemblyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler for {0} does not support the /delaysign option..
        /// </summary>
        internal static string String_CompilerDoesNotSupportDelaySign {
            get {
                return ResourceManager.GetString("String_CompilerDoesNotSupportDelaySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler for {0} does not support the /keycontainer option..
        /// </summary>
        internal static string String_CompilerDoesNotSupportKeyContainer {
            get {
                return ResourceManager.GetString("String_CompilerDoesNotSupportKeyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler for {0} does not support the /keyfile option..
        /// </summary>
        internal static string String_CompilerDoesNotSupportKeyFile {
            get {
                return ResourceManager.GetString("String_CompilerDoesNotSupportKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler for &quot;{0}&quot; does not support accepting only a specific language syntax..
        /// </summary>
        internal static string String_CompilerDoesNotSupportLangVersion {
            get {
                return ResourceManager.GetString("String_CompilerDoesNotSupportLangVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler for &quot;{0}&quot; does not support the /nostdlib option..
        /// </summary>
        internal static string String_CompilerDoesNotSupportNoStdLib {
            get {
                return ResourceManager.GetString("String_CompilerDoesNotSupportNoStdLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler for {0} does not support package references..
        /// </summary>
        internal static string String_CompilerDoesNotSupportPackageReferences {
            get {
                return ResourceManager.GetString("String_CompilerDoesNotSupportPackageReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler for &quot;{0}&quot; does not support limiting the platform on which the compiled code can run..
        /// </summary>
        internal static string String_CompilerDoesNotSupportPlatform {
            get {
                return ResourceManager.GetString("String_CompilerDoesNotSupportPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler for {0} does not support a command line option to specify a list of warnings to treat as errors..
        /// </summary>
        internal static string String_CompilerDoesNotSupportWarningsAsErrors {
            get {
                return ResourceManager.GetString("String_CompilerDoesNotSupportWarningsAsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler for {0} does not support a command line option to specify a list of warnings to suppress..
        /// </summary>
        internal static string String_CompilerDoesNotSupportWarningsToSuppress {
            get {
                return ResourceManager.GetString("String_CompilerDoesNotSupportWarningsToSuppress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler for &quot;{0}&quot; does not support generation of XML Documentation file..
        /// </summary>
        internal static string String_CompilerDoesNotSupportXmlDoc {
            get {
                return ResourceManager.GetString("String_CompilerDoesNotSupportXmlDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling {0} files to &apos;{1}&apos;..
        /// </summary>
        internal static string String_CompilingFiles {
            get {
                return ResourceManager.GetString("String_CompilingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling license file &apos;{0}&apos; to &apos;{1}&apos; using target &apos;{2}&apos;..
        /// </summary>
        internal static string String_CompilingLicenseUsingTarget {
            get {
                return ResourceManager.GetString("String_CompilingLicenseUsingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents of {0}..
        /// </summary>
        internal static string String_ContentsOf {
            get {
                return ResourceManager.GetString("String_ContentsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new license file {0}..
        /// </summary>
        internal static string String_CreatedNewLicense {
            get {
                return ResourceManager.GetString("String_CreatedNewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating COM+ application &apos;{0}&apos;..
        /// </summary>
        internal static string String_CreatingCOM_Application {
            get {
                return ResourceManager.GetString("String_CreatingCOM+Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating licenses ....
        /// </summary>
        internal static string String_CreatingLicenses {
            get {
                return ResourceManager.GetString("String_CreatingLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay-signing {0} assemblies..
        /// </summary>
        internal static string String_DelaySigningAssemblies {
            get {
                return ResourceManager.GetString("String_DelaySigningAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find dependent file {0}..
        /// </summary>
        internal static string String_DependentFileNotFound {
            get {
                return ResourceManager.GetString("String_DependentFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc file &apos;{0}&apos; does not exist, recompiling..
        /// </summary>
        internal static string String_DocFileDoesNotExist {
            get {
                return ResourceManager.GetString("String_DocFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has been updated, recompiling..
        /// </summary>
        internal static string String_FileHasBeenUpdated {
            get {
                return ResourceManager.GetString("String_FileHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is up-to-date..
        /// </summary>
        internal static string String_FileUpToDate {
            get {
                return ResourceManager.GetString("String_FileUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding or creating COM+ application &apos;{0}&apos;..
        /// </summary>
        internal static string String_FindingCOM_Application {
            get {
                return ResourceManager.GetString("String_FindingCOM+Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found resource linkage &apos;{0}&apos; in dependent file &apos;{1}&apos;..
        /// </summary>
        internal static string String_FoundResourceLinkageInDependentFile {
            get {
                return ResourceManager.GetString("String_FoundResourceLinkageInDependentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated code for the script looks like:.
        /// </summary>
        internal static string String_GeneratedCodeLooksLike {
            get {
                return ResourceManager.GetString("String_GeneratedCodeLooksLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated file &apos;{0}&apos;..
        /// </summary>
        internal static string String_GeneratedFile {
            get {
                return ResourceManager.GetString("String_GeneratedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JScript.NET compiler does not support linking modules..
        /// </summary>
        internal static string String_JscDoesNotSupportLinkingModules {
            get {
                return ResourceManager.GetString("String_JscDoesNotSupportLinkingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly linker for {0} does not support a command line option to specify an assembly from which to get all options except the culture field..
        /// </summary>
        internal static string String_LinkerDoesNotSupportTemplateAssembly {
            get {
                return ResourceManager.GetString("String_LinkerDoesNotSupportTemplateAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading assemblies ....
        /// </summary>
        internal static string String_LoadingAssemblies {
            get {
                return ResourceManager.GetString("String_LoadingAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDoc project file: file://{0}.
        /// </summary>
        internal static string String_NDocProjectFile {
            get {
                return ResourceManager.GetString("String_NDocProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file &apos;{0}&apos; does not exist, rebuilding..
        /// </summary>
        internal static string String_OutputFileDoesNotExist {
            get {
                return ResourceManager.GetString("String_OutputFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file &apos;{0}&apos; is not up-to-date, rebuilding..
        /// </summary>
        internal static string String_OutputFileNotUpToDate {
            get {
                return ResourceManager.GetString("String_OutputFileNotUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % complete.
        /// </summary>
        internal static string String_PercentageComplete {
            get {
                return ResourceManager.GetString("String_PercentageComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;rebuild&apos; attribute set to true, recompiling..
        /// </summary>
        internal static string String_RebuildAttributeSetToTrue {
            get {
                return ResourceManager.GetString("String_RebuildAttributeSetToTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource compiler for {0} does not support external file references..
        /// </summary>
        internal static string String_ResourceCompilerDoesNotSupportExternalReferences {
            get {
                return ResourceManager.GetString("String_ResourceCompilerDoesNotSupportExternalReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any resource linkage in dependent file &apos;{0}&apos;..
        /// </summary>
        internal static string String_ResourceLinkageInDependentFileNotFound {
            get {
                return ResourceManager.GetString("String_ResourceLinkageInDependentFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling COM+ application &apos;{0}&apos;..
        /// </summary>
        internal static string String_UninstallingCOM_Application {
            get {
                return ResourceManager.GetString("String_UninstallingCOM+Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing project settings to &apos;{0}&apos;..
        /// </summary>
        internal static string String_WritingProjectSettings {
            get {
                return ResourceManager.GetString("String_WritingProjectSettings", resourceCulture);
            }
        }
    }
}
