name: NAnt2 build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Project name to pack and publish
  PROJECT_NAME: NAnt2
  #Project version
  PROJECT_VERSION: 0.95

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Ensure .NET SDK availability
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
          dotnet-quality: 'ga'
      - name: Build and test
        shell: pwsh
        run: .\build.ps1 -Tasks Build -BuildConfiguration Debug -Rebuild