name: NAnt2 build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Project name to pack and publish
  PROJECT_NAME: NAnt2
  #Project version
  PROJECT_VERSION: 0.95

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-20.04, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Ensure .NET SDK availability
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
          dotnet-quality: 'ga'
      - name: Build
        shell: pwsh
        run: .\build.ps1 -Tasks Build -BuildConfiguration Debug -Rebuild
      - name: Run tests
        if: runner.os == 'Windows'
        shell: pwsh
        run: .\build.ps1 -Tasks Test -BuildConfiguration Debug -Rebuild -WithCoverage
      - name: ${{matrix.os}} Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: runner.os == 'Windows'
        with:
          comment_mode: off
          files: 
            reports/nant.test.trx
      - name: ${{matrix.os}} Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: runner.os == 'Windows'
        with:
          filename: reports/coverage.cobertura.xml
          badge: true
          format: 'markdown'
          output: 'both'
      - name: Write to Job Summary
        if: runner.os == 'Windows'
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY